#gp2s:
#  auth:
#    ldap:
#      url: ldap://localhost:10389
#      managerDn: uid=admin,ou=system
#      managerPassword: password
#      userSearchQuery: uid={0}
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gp2sdb?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: pppppppp
    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          default_schema: gp2sdb
          dialect: org.hibernate.dialect.MySQLDialect
          use_jdbc_metadata_defaults: false
          format_sql: true
          order_by.default_null_ordering: last

  data:
    mongodb:
      uri: mongodb://localhost:27017/gp2sdb
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/public-gp2s/dev/

  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

swagger:
  info:
    title: gP2S REST API
    description: gP2S description
    version: 1
    contactName: gP2S Team
    url: 
    e-mail:

server:
  servlet:
    context-path: /gp2s
  port: 21113
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

ribbon:
  eureka:
   enabled: false

logging:
  level:
    root: INFO
    com.gene.bioinfo.ms.gp2s: INFO

management:
  endpoint:
    shutdown:
      enabled: true

  health:
    ldap:
      enabled: false